Repository asc-community/MxEngine, pull requests merged in 2023-07, with the labels that each got.

#88 [Rendering] Fix SSGI algorithm
  samples/Sponza/sponza.json
  src/Core/Components/Camera/CameraSSGI.h
  src/Platform/OpenGL/Shaders/ssgi_fragment.glsl
Labels: bug

#90 Revert "[CI] add build artefacts to appveryor"
  .appveyor.yml
Labels: build

#93 [Model loading] fix alpha cutoff affect transparency even when render mode is opaque
  samples/Sponza/Resources/Sponza/glTF/Sponza.gltf.mx_matlib
  src/Utilities/ObjectLoading/ObjectLoader.cpp
Labels: bug

#89 [Rendering] correct dirlight shadows (with cascades)
  preview_images/readme_main.png
  preview_images/readme_main_v800.png
  samples/Doom/scene.json
  samples/Particles/scene.json
  samples/PhysicsSample/MxApplication.cpp
  samples/SandboxApplication/Gameplay/CameraObject.cpp
  samples/Sponza/sponza.json
  src/Core/BoundingObjects/FrustrumCuller.h
  src/Core/Components/Camera/CameraController.cpp
  src/Core/Components/Lighting/DirectionalLight.cpp
  src/Core/Components/Lighting/DirectionalLight.h
  src/Core/MxObject/MxObject.h
  src/Core/Rendering/DebugDataSubmitter.cpp
  src/Core/Rendering/RenderController.cpp
  src/Core/Rendering/RenderController.h
  src/Core/Rendering/RenderUtilities/ShadowMapGenerator.cpp
  src/Core/Runtime/RuntimeEditor.cpp
  src/Platform/OpenGL/Renderer.cpp
  src/Platform/OpenGL/Renderer.h
  src/Platform/OpenGL/Shaders/Library/directional_light.glsl
  src/Platform/OpenGL/Shaders/Library/shader_utils.glsl
  src/Platform/OpenGL/Shaders/spotlight_fragment.glsl
Labels: enhancement
